In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

In [3]:
movies.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466

In [4]:
movies.shape

(4803, 20)

In [5]:
credits.head(3)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [6]:
movies = movies.merge(credits, on='title')

In [7]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [8]:
# buget 
# homepage
# id
# original_language
# original_title
# popularity
# production_companies

In [9]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [10]:
movies.sample(1)

,movie_id,title,overview,genres,keywords,cast,crew
2965,14395,Kabhi Alvida Naa Kehna,Dev and Maya are both married to different peo...,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...","[{""id"": 596, ""name"": ""adultery""}, {""id"": 34094...","[{""cast_id"": 1, ""character"": ""Dev Saran"", ""cre...","[{""credit_id"": ""58a5e57892514152a70006bf"", ""de..."

In [11]:
import ast

In [12]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name'])
    return L

In [13]:
movies.dropna(inplace=True)

In [14]:
movies['genres'] = movies['genres'].apply(convert)

In [15]:
movies['keywords'] = movies['keywords'].apply(convert)

In [16]:
movies.sample(3)

,movie_id,title,overview,genres,keywords,cast,crew
3267,59930,The Inkwell,The Inkwell is about a 16-year-old boy coming ...,"[Comedy, Drama, Romance]",[],"[{""cast_id"": 1001, ""character"": ""Drew Tate"", ""...","[{""credit_id"": ""52fe49a2c3a36847f81a480b"", ""de..."
1761,9549,The Right Stuff,A chronicle of the original Mercury astronauts...,"[Drama, History]","[cold war, pilot, space travel, politics, hist...","[{""cast_id"": 5, ""character"": ""Gus Grissom"", ""c...","[{""credit_id"": ""52fe4508c3a36847f80b851d"", ""de..."
429,7518,Over the Hedge,A scheming raccoon fools a mismatched family o...,"[Comedy, Animation, Family]","[squirrel, eating and drinking, vororte, garde...","[{""cast_id"": 1, ""character"": ""RJ (voice)"", ""cr...","[{""credit_id"": ""52fe4482c3a36847f809a535"", ""de..."

In [17]:
movies['cast'] = movies['cast'].apply(convert)

In [18]:
movies.head(3)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [19]:
movies['cast'] = movies['cast'].apply(lambda x:x[0:3])

In [20]:
movies.sample(3)

,movie_id,title,overview,genres,keywords,cast,crew
4372,13508,Who Killed the Electric Car?,"In 1996, electric cars began to appear on road...",[Documentary],"[energy supply, automobile industry, independe...","[Martin Sheen, Mel Gibson, Tom Hanks]","[{""credit_id"": ""52fe45739251416c75056f3b"", ""de..."
2442,10629,Veronica Guerin,"In this true story, Veronica Guerin is an inve...","[Drama, Crime, Thriller]","[journalism, police, drug scene, murder, drug ...","[Cate Blanchett, Gerard McSorley, Ciarán Hinds]","[{""credit_id"": ""52fe43989251416c75016875"", ""de..."
4757,42109,Gabriela,"In 1925, Gabriela becomes cook, mistress, and ...","[Drama, Romance]",[],"[Sônia Braga, Marcello Mastroianni, Antonio Ca...","[{""credit_id"": ""590dc620c3a36864c600e4e4"", ""de..."

In [21]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [22]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [23]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [24]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [25]:
movies.sample(3)

,movie_id,title,overview,genres,keywords,cast,crew
3441,5708,Control,"[Control, is, the, biography, of, Joy, Divisio...",[Drama],"[manchester city, medicine, new love, epilepsy...","[Sam Riley, Samantha Morton, Alexandra Maria L...",[Anton Corbijn]
315,1734,The Mummy Returns,"[Rick, and, Evelyn, O'Connell,, along, with, t...","[Adventure, Action, Fantasy]","[son, ancient egypt, bracelet]","[Brendan Fraser, Rachel Weisz, John Hannah]",[Stephen Sommers]
4292,46256,The Lion of Judah,"[Upon, learning, that, Judah, has, been, trapp...","[Adventure, Animation, Comedy, Family]","[palm sunday, jerusalem judah, bethlehem judah]","[Georgina Cordova, Ernest Borgnine, Michael Ma...",[Deryck Broom]

In [26]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [27]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [28]:
movies['cast'][0]

['SamWorthington', 'ZoeSaldana', 'SigourneyWeaver']

In [29]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]

In [30]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [31]:
movies.sample(2)

,movie_id,title,overview,genres,keywords,cast,crew,tags
3853,540,D.E.B.S.,"[The, star, of, a, team, of, teenage, crime, f...",[Action],"[comingout, covertoperation, lesbian, femalepr...","[SaraFoster, MeaganGood, JordanaBrewster]",[AngelaRobinson],"[The, star, of, a, team, of, teenage, crime, f..."
2904,50601,5 Days of War,"[An, American, journalist, and, his, cameraman...","[War, Drama]","[journalist, interpreter, georgiaeurope, warzone]","[RupertFriend, ValKilmer, AndyGarcía]",[RennyHarlin],"[An, American, journalist, and, his, cameraman..."

In [32]:
new = movies.drop(columns =['overview','genres','keywords','cast','crew'])

In [33]:
new['tags'] = new['tags'].apply(lambda x: " ".join(x))

In [34]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [35]:
vector = cv.fit_transform(new['tags']).toarray()

In [36]:
vector.shape

(4806, 5000)

In [37]:
from sklearn.metrics.pairwise import cosine_similarity

In [38]:
similarity = cosine_similarity(vector)

In [39]:
similarity

array([[1.        , 0.08964215, 0.06071767, ..., 0.02519763, 0.0277885 ,
        0.        ],
       [0.08964215, 1.        , 0.06350006, ..., 0.02635231, 0.        ,
        0.        ],
       [0.06071767, 0.06350006, 1.        , ..., 0.02677398, 0.        ,
        0.        ],
       ...,
       [0.02519763, 0.02635231, 0.02677398, ..., 1.        , 0.07352146,
        0.04774099],
       [0.0277885 , 0.        , 0.        , ..., 0.07352146, 1.        ,
        0.05264981],
       [0.        , 0.        , 0.        , ..., 0.04774099, 0.05264981,
        1.        ]], shape=(4806, 4806))

In [40]:
new[new['title'] == 'The Lego Movie'].index[0]

np.int64(744)

In [41]:
def recommend(movie):
    index = new[new['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True, key=lambda x: x[1])
    for i in distances[1:6]:
        print(new.iloc[i[0]].title)

In [42]:
recommend('Gandhi')

Gandhi, My Father
The Wind That Shakes the Barley
A Passage to India
Guiana 1838
Ramanujan

In [43]:
import pickle

In [44]:
pickle.dump(new,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))